
# hotdog-constest-winners.xlsm
# hotdog-places.xlsm
# obama-approval-ratings.xls
# setwd("C:/Users/Rochjo1")

library(ggplot2)
library(readxl)
library(tidyverse)

hotdog<- read_excel("hotdog-contest-winners.xlsm")
head(hotdog)

view(hotdog)

# online Library
library(RColorBrewer)
coul <- brewer.pal(5, "Set2") 
countrys <- table(hotdog$Country)

barplot(countrys, main='Countries in Hot Dog Eaten Contest', col=coul, xlab="Country", 
        ylab="Times Entered", )
        
        
dogs <- hotdog$`Dogs eaten`
country2 <- hotdog$Country
ggplot(hotdog, aes(fill = Winner, y = dogs, x = country2)) + geom_bar(position = 'stack', stat = 'identity') + labs( x = 'Countries Part of Contest', y = 'Hot Dogs Eaten ', title = 'Hot Dogs Eaten According to Country and Winners')

myPalette <- brewer.pal(4, "Set2") 
pie(countrys,col=myPalette,border="white")


obama<-read_excel("obama-approval-ratings.xls")
head(obama)
view(obama)

## Had to find online, it was actually hard to figure out more than the others. 

obama_long = obama %>%
    tidyr::gather('Reaction','Ratings', Approve, Disapprove, None)
obama_long %>%
    dplyr::filter(Issue=='Immigration') %>%
    dplyr::mutate(ymax=cumsum(Ratings),
                  ymin=c(0,ymax[1:length(ymax)-1])) %>%
    ggplot2::ggplot(ggplot2::aes(fill=Reaction, ymax=ymax, ymin=ymin, xmax=4, xmin=3)) +
         ggplot2::geom_rect() +
         ggplot2::coord_polar(theta='y') +
         ggplot2::xlim(c(0, 4)) +
         ggplot2::theme(panel.grid=element_blank()) +
         ggplot2::theme(axis.text=element_blank()) +
         ggplot2::theme(axis.ticks=element_blank()) +
         ggplot2::annotate('text', x = 0, y = 0, label = 'Reaction on Immigration') +
         ggplot2::labs(title='')

